import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/screens/**/*.{js,ts,jsx,tsx,mdx}',
    './src/layouts/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#eeefff',
        'tertiary-fixed': '#ffdbcd',
        'surface-container': '#ededf9',
        'surface-dim': '#d9d9e5',
        'tertiary-container': '#bc4800',
        'surface-bright': '#faf8ff',
        'on-tertiary-container': '#ffede6',
        'surface-variant': '#e1e2ed',
        'inverse-on-surface': '#f0f0fb',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#005049',
        'on-surface': '#191b23',
        background: '#faf8ff',
        'on-background': '#191b23',
        'on-primary-fixed-variant': '#003ea8',
        'primary-fixed-dim': '#b4c5ff',
        'on-secondary-fixed': '#00201d',
        'on-secondary-container': '#006f66',
        secondary: '#006a61',
        'primary-container': '#2563eb',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#00174b',
        'tertiary-fixed-dim': '#ffb596',
        'surface-container-highest': '#e1e2ed',
        'secondary-container': '#86f2e4',
        tertiary: '#943700',
        'outline-variant': '#c3c6d7',
        'on-tertiary-fixed': '#360f00',
        'inverse-primary': '#b4c5ff',
        'on-secondary': '#ffffff',
        outline: '#737686',
        'inverse-surface': '#2e3039',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#7d2d00',
        'surface-container-high': '#e7e7f3',
        primary: '#004ac6',
        'on-surface-variant': '#434655',
        'secondary-fixed': '#89f5e7',
        'surface-container-low': '#f3f3fe',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#6bd8cb',
        'on-error-container': '#93000a',
        'surface-tint': '#0053db',
        surface: '#faf8ff',
        'primary-fixed': '#dbe1ff',
        'on-error': '#ffffff',

        // System fallbacks
        canvas: 'var(--color-canvas)',
        'surface-subtle': 'var(--color-surface-subtle)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        accent: 'var(--color-accent)',
        'accent-subtle': 'var(--color-accent-subtle)',
        verified: 'var(--color-verified)',
        'verified-subtle': 'var(--color-verified-subtle)',
        warning: 'var(--color-warning)',
        'warning-subtle': 'var(--color-warning-subtle)',
        critical: 'var(--color-critical)',
        'critical-subtle': 'var(--color-critical-subtle)',
        ayush: 'var(--color-ayush)',
        'ayush-subtle': 'var(--color-ayush-subtle)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        base: '4px',
        lg: '24px',
        xl: '32px',
        gutter: '16px',
        'container-max': '1440px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'page-title': ["'hankenGrotesk'", "'Hanken Grotesk'", "'Plus Jakarta Sans'", 'sans-serif'],
        'section-heading': ["'hankenGrotesk'", "'Hanken Grotesk'", "'Plus Jakarta Sans'", 'sans-serif'],
        'body-compact': ["'plusJakartaSans'", "'Plus Jakarta Sans'", 'sans-serif'],
        'body-primary': ["'plusJakartaSans'", "'Plus Jakarta Sans'", 'sans-serif'],
        'metadata-mono': ["'jetbrainsMono'", "'JetBrains Mono'", 'monospace'],
        'display-lg': ["'hankenGrotesk'", "'Hanken Grotesk'", 'sans-serif'],
        sans: ['var(--font-sans)', "'Plus Jakarta Sans'", 'sans-serif'],
        mono: ['var(--font-mono)', "'JetBrains Mono'", 'monospace'],
        display: ['var(--font-display)', "'Hanken Grotesk'", 'sans-serif'],
      },
      fontSize: {
        'page-title': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'section-heading': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-compact': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-primary': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'metadata-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0,0,0,0.05)',
        md: '0 4px 12px rgba(0,0,0,0.08)',
        lg: '0 12px 32px rgba(0,0,0,0.10)',
        drawer: '-4px 0 32px rgba(0,0,0,0.08)',
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
